### PR TITLE
Issue of background image getting vertically repeated fixed

### LINKED ISSUE #2: Bug: Background Image is getting repeated in screens having height greater than 740 pixels
I'm submitting a 
- [x] bug report
- [ ] feature request

**Current behavior:**
 Background image is getting vertically repeated in screens having height greater than 740 pixels

image

**Expected behavior:**
Background image should not get vertically repeated and it should spread entirely in the area available as a whole

### PR DESCRIPTION
**Pull request by adit19shah**
**Fixes Issue**
Fixes: #2 

**Condition before fixing the issue**

image

**Condition after fixing the issue**

image

### CODE REVIEW

**Review by iamsonukushwaha — APPROVED** [review]
Thanks for contributing!

**Comment by adit19shah** [comment]
@flyingsonu122 Can you please add Hacktoberfest label to it ? so that my PR gets counted towards the Hacktoberfest 2020.

**Comment by adit19shah** [comment]
@flyingsonu122, Sorry to bother you once again. But I think there is some spelling error. Shouldn't it be "hacktoberfest" instead of "hactoberfest" in the labels over here as well as repository-topics ?

**Comment by iamsonukushwaha** [comment]
it was a TYPO

Thanks buddy !

**Comment by adit19shah** [comment]
You're Welcome !

**Pull request merged**
